<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'phone',
        'role',
        'department',
        'designation',
        'employee_id',
        'avatar',
        'is_active',
        'last_login_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'last_login_at' => 'datetime',
            'password' => 'hashed',
            'is_active' => 'boolean',
        ];
    }

    /**
     * Check if user is director
     */
    public function isDirector(): bool
    {
        return $this->role === 'director';
    }

    /**
     * Check if user is PA
     */
    public function isPA(): bool
    {
        return $this->role === 'pa';
    }

    /**
     * Check if user is admin
     */
    public function isAdmin(): bool
    {
        return $this->role === 'admin';
    }

    /**
     * Check if user is staff
     */
    public function isStaff(): bool
    {
        return $this->role === 'staff';
    }

    /**
     * Appointments received by this director
     */
    public function appointmentsAsDirector()
    {
        return $this->hasMany(Appointment::class, 'director_id');
    }

    /**
     * Appointments created by this user
     */
    public function appointmentsCreated()
    {
        return $this->hasMany(Appointment::class, 'created_by');
    }

    /**
     * Meeting schedules for this director
     */
    public function meetingSchedules()
    {
        return $this->hasMany(MeetingSchedule::class, 'director_id');
    }

    /**
     * Availability rules for this director
     */
    public function availabilityRules()
    {
        return $this->hasMany(DirectorAvailability::class, 'director_id');
    }

    /**
     * Blocked dates for this director
     */
    public function blockedDates()
    {
        return $this->hasMany(BlockedDate::class, 'director_id');
    }

    /**
     * Daily logbooks for this director
     */
    public function dailyLogbooks()
    {
        return $this->hasMany(DailyLogbook::class, 'director_id');
    }

    /**
     * Todos for this user
     */
    public function todos()
    {
        return $this->hasMany(Todo::class, 'user_id');
    }

    /**
     * Journal entries for this user
     */
    public function journalEntries()
    {
        return $this->hasMany(JournalEntry::class, 'user_id');
    }

    /**
     * Reports generated by this user
     */
    public function generatedReports()
    {
        return $this->hasMany(GeneratedReport::class, 'generated_by');
    }

    /**
     * Notification preferences for this user
     */
    public function notificationPreferences()
    {
        return $this->hasOne(NotificationPreference::class, 'user_id');
    }

    /**
     * Scope for active users
     */
    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    /**
     * Scope for directors only
     */
    public function scopeDirectors($query)
    {
        return $query->where('role', 'director');
    }

    /**
     * Scope for PA users only
     */
    public function scopePAs($query)
    {
        return $query->where('role', 'pa');
    }
}
